#!/usr/bin/env python3
"""Generate src/keycodes.h from linux/input-event-codes.h.

    tools/gen-keycodes.py /usr/include/linux/input-event-codes.h > src/keycodes.h

Emits every KEY_* and BTN_* identifier with its numeric value, aliases
resolved, sorted by name, as a static table the bridge uses to turn config
key names into codes. Runs at build time so the table always matches the
kernel headers it was built against (spec §6).
"""
import re
import sys

DEFINE = re.compile(r"^#define\s+((?:KEY|BTN)_[A-Z0-9_]+)\s+(\S+)")
EXCLUDE = {"KEY_MAX", "KEY_CNT", "KEY_RESERVED"}


def main(path):
    values = {}
    for line in open(path, encoding="utf-8"):
        m = DEFINE.match(line)
        if not m:
            continue
        name, raw = m.groups()
        raw = raw.split("/*")[0].strip()
        if raw in values:
            values[name] = values[raw]
            continue
        try:
            values[name] = int(raw, 0)
        except ValueError:
            print(f"gen-keycodes: skipping {name} = {raw}", file=sys.stderr)
    key_max = values.get("KEY_MAX", 0x2FF)
    entries = sorted(
        (n, v) for n, v in values.items() if n not in EXCLUDE and 0 < v <= key_max
    )
    out = [
        "/* Generated by tools/gen-keycodes.py; do not edit. */",
        "#ifndef TACET_KEYCODES_H",
        "#define TACET_KEYCODES_H",
        "#include <stdint.h>",
        "typedef struct keycode_name { const char *name; uint16_t code; } keycode_name;",
        f"#define KEYCODE_NAME_COUNT {len(entries)}",
        f"#define KEYCODE_MAX {key_max}",
        "static const keycode_name keycode_names[KEYCODE_NAME_COUNT] = {",
    ]
    out += [f'    {{ "{n}", {v} }},' for n, v in entries]
    out += ["};", "#endif", ""]
    sys.stdout.write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "/usr/include/linux/input-event-codes.h"))
